#%YAML:1.0
---
camera_name: MULTI_RGBD_INERTIAL_DATASET_REAR
image_width: 640
image_height: 360
camera_matrix:
   rows: 3
   cols: 3
   data: [ 319.3360, 0., 323.9265, 0.,
       319.1947, 181.9133, 0., 0., 1. ]
distortion_coefficients:
   rows: 1
   cols: 4
   data: [ -0.0534, 0.0542, -0.0155, 0.0 ]
distortion_model: plumb_bob
rectification_matrix:
   rows: 3
   cols: 3
   data: [ 1., 0., 0., 
       0., 1., 0.,
       0., 0., 1. ]
projection_matrix:
   rows: 3
   cols: 4
   data: [ 319.3360, 0., 323.9265, 0., 0.,
       319.1947, 181.9133, 0., 0., 0., 1.,
       0. ]